---
- name: Install NFS server
  hosts: kubernetes
  become: true
  tasks:
    - name: Install NFS server
      package:
        name: nfs-kernel-server
        state: present

    - name: Start NFS server
      service:
        name: nfs-kernel-server
        state: started
        enabled: yes
